# Generated by Django 5.1.4 on 2025-01-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_time_update'),
        ('tovars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Category',
        ),
    ]
