# Generated by Django 5.1.4 on 2025-01-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_shippingaddress_order_orders_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
