# Generated by Django 5.1.4 on 2025-01-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='tovar',
        ),
    ]
